### ISSUE TITLE
Upgrade broccoli-replace dependency when their Issue #10 is resolved

### ISSUE THREAD

**Issue by notmessenger** [ember-redux/ember-redux-shim#28]
Once https://github.com/outaTiME/broccoli-replace/issues/10 is resolved this repo's dependency on the `applause` dependency should be upgraded to address the

> coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

deprecation.

**Comment by outaTiME** [comment]
broccoli-replace gets updated https://github.com/outaTiME/broccoli-replace/releases/tag/2.0.1, you could close this issue
