### ISSUE TITLE
NPM owner access request? (redux)

### ISSUE THREAD

**Issue by toranb** [ember-redux/ember-redux-shim#3]
@sandersky I realize that @MiguelMadero and I are both github contributors but what would it take to get NPM access also (as shared ownership of this becomes more important) ?

`npm owner add toranb ember-redux-shim`

`npm owner add ? ember-redux-shim` (not sure what @MiguelMadero is using for his npm handle)

**Comment by MiguelMadero** [comment]
Miguelmadero

https://www.npmjs.com/~miguelmadero
